set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 6 [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR NO [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]

create_clock -period 8.333 -name FPGA_CLK -waveform {0.000 4.167} [get_ports FPGA_CLK]

set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports FPGA_CLK]

set_property -dict { PACKAGE_PIN F5 IOSTANDARD LVCMOS18 } [get_ports { ADC_CLKOUT }]
set_property -dict { PACKAGE_PIN L3 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[0] }]
set_property -dict { PACKAGE_PIN L2 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[1] }]
set_property -dict { PACKAGE_PIN K2 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[2] }]
set_property -dict { PACKAGE_PIN K3 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[3] }]
set_property -dict { PACKAGE_PIN K1 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[4] }]
set_property -dict { PACKAGE_PIN K5 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[5] }]
set_property -dict { PACKAGE_PIN J3 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[6] }]
set_property -dict { PACKAGE_PIN J1 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[7] }]
set_property -dict { PACKAGE_PIN J4 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[8] }]
set_property -dict { PACKAGE_PIN H2 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[9] }]
set_property -dict { PACKAGE_PIN J5 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[10] }]
set_property -dict { PACKAGE_PIN H3 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[11] }]
set_property -dict { PACKAGE_PIN G1 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[12] }]
set_property -dict { PACKAGE_PIN G2 IOSTANDARD LVCMOS18 } [get_ports { ADC_DA[13] }]
set_property -dict { PACKAGE_PIN H4 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[0] }]
set_property -dict { PACKAGE_PIN F2 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[1] }]
set_property -dict { PACKAGE_PIN E1 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[2] }]
set_property -dict { PACKAGE_PIN F3 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[3] }]
set_property -dict { PACKAGE_PIN F4 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[4] }]
set_property -dict { PACKAGE_PIN D1 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[5] }]
set_property -dict { PACKAGE_PIN E2 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[6] }]
set_property -dict { PACKAGE_PIN E3 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[7] }]
set_property -dict { PACKAGE_PIN C1 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[8] }]
set_property -dict { PACKAGE_PIN D3 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[9] }]
set_property -dict { PACKAGE_PIN D4 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[10] }]
set_property -dict { PACKAGE_PIN B1 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[11] }]
set_property -dict { PACKAGE_PIN B2 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[12] }]
set_property -dict { PACKAGE_PIN A2 IOSTANDARD LVCMOS18 } [get_ports { ADC_DB[13] }]

set_property -dict { PACKAGE_PIN T7 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[0] }]
set_property -dict { PACKAGE_PIN P8 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[1] }]
set_property -dict { PACKAGE_PIN R8 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[2] }]
set_property -dict { PACKAGE_PIN T8 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[3] }]
set_property -dict { PACKAGE_PIN P9 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[4] }]
set_property -dict { PACKAGE_PIN T9 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[5] }]
set_property -dict { PACKAGE_PIN T10 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[6] }]
set_property -dict { PACKAGE_PIN R10 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[7] }]
set_property -dict { PACKAGE_PIN P10 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[8] }]
set_property -dict { PACKAGE_PIN R11 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[9] }]
set_property -dict { PACKAGE_PIN P11 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[10] }]
set_property -dict { PACKAGE_PIN T12 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[11] }]
set_property -dict { PACKAGE_PIN R12 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[12] }]
set_property -dict { PACKAGE_PIN T13 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[13] }]
set_property -dict { PACKAGE_PIN R13 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[14] }]
set_property -dict { PACKAGE_PIN T14 IOSTANDARD LVCMOS33 } [get_ports { DAC_DA[15] }]
set_property -dict { PACKAGE_PIN R7 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[0] }]
set_property -dict { PACKAGE_PIN R6 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[1] }]
set_property -dict { PACKAGE_PIN P6 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[2] }]
set_property -dict { PACKAGE_PIN T5 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[3] }]
set_property -dict { PACKAGE_PIN R5 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[4] }]
set_property -dict { PACKAGE_PIN P5 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[5] }]
set_property -dict { PACKAGE_PIN T4 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[6] }]
set_property -dict { PACKAGE_PIN P4 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[7] }]
set_property -dict { PACKAGE_PIN R3 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[8] }]
set_property -dict { PACKAGE_PIN T3 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[9] }]
set_property -dict { PACKAGE_PIN N4 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[10] }]
set_property -dict { PACKAGE_PIN P3 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[11] }]
set_property -dict { PACKAGE_PIN T2 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[12] }]
set_property -dict { PACKAGE_PIN R2 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[13] }]
set_property -dict { PACKAGE_PIN R1 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[14] }]
set_property -dict { PACKAGE_PIN N3 IOSTANDARD LVCMOS33 } [get_ports { DAC_DB[15] }]
set_property -dict { PACKAGE_PIN D8 IOSTANDARD LVCMOS33 } [get_ports { DAC_PHSTR }]

set_property -dict { PACKAGE_PIN M2 IOSTANDARD LVCMOS33 } [get_ports { SCK }]
set_property -dict { PACKAGE_PIN L4 IOSTANDARD LVCMOS33 } [get_ports { SDI }]
set_property -dict { PACKAGE_PIN M1 IOSTANDARD LVCMOS33 } [get_ports { SDO }]
set_property -dict { PACKAGE_PIN L5 IOSTANDARD LVCMOS33 } [get_ports { SEN }]

set_property -dict { PACKAGE_PIN A14 IOSTANDARD LVCMOS33 } [get_ports { FMC_ALE }]
set_property -dict { PACKAGE_PIN C13 IOSTANDARD LVCMOS33 } [get_ports { FMC_CLE }]
set_property -dict { PACKAGE_PIN B12 IOSTANDARD LVCMOS33 } [get_ports { FMC_NCE }]
set_property -dict { PACKAGE_PIN B11 IOSTANDARD LVCMOS33 } [get_ports { FMC_NOE }]
set_property -dict { PACKAGE_PIN C11 IOSTANDARD LVCMOS33 } [get_ports { FMC_NWE }]
set_property -dict { PACKAGE_PIN B14 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[0] }]
set_property -dict { PACKAGE_PIN C14 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[1] }]
set_property -dict { PACKAGE_PIN A12 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[2] }]
set_property -dict { PACKAGE_PIN C12 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[3] }]
set_property -dict { PACKAGE_PIN C8 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[4] }]
set_property -dict { PACKAGE_PIN A8 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[5] }]
set_property -dict { PACKAGE_PIN C9 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[6] }]
set_property -dict { PACKAGE_PIN D9 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[7] }]
set_property -dict { PACKAGE_PIN A9 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[8] }]
set_property -dict { PACKAGE_PIN B9 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[9] }]
set_property -dict { PACKAGE_PIN B10 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[10] }]
set_property -dict { PACKAGE_PIN A10 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[11] }]
set_property -dict { PACKAGE_PIN E12 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[12] }]
set_property -dict { PACKAGE_PIN D13 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[13] }]
set_property -dict { PACKAGE_PIN A13 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[14] }]
set_property -dict { PACKAGE_PIN E13 IOSTANDARD LVCMOS33 } [get_ports { FSMC_D[15] }]

set_property -dict { PACKAGE_PIN A7 IOSTANDARD LVCMOS18 } [get_ports { GRINX[0] }]
set_property -dict { PACKAGE_PIN B6 IOSTANDARD LVCMOS18 } [get_ports { GRINX[1] }]
set_property -dict { PACKAGE_PIN B5 IOSTANDARD LVCMOS18 } [get_ports { GRINY[0] }]
set_property -dict { PACKAGE_PIN A5 IOSTANDARD LVCMOS18 } [get_ports { GRINY[1] }]
set_property -dict { PACKAGE_PIN A4 IOSTANDARD LVCMOS18 } [get_ports { GRINZ[0] }]
set_property -dict { PACKAGE_PIN B4 IOSTANDARD LVCMOS18 } [get_ports { GRINZ[1] }]

set_property -dict { PACKAGE_PIN B7 IOSTANDARD LVCMOS18 } [get_ports { IO[0] }]
set_property -dict { PACKAGE_PIN H5 IOSTANDARD LVCMOS18 } [get_ports { IO[1] }]
set_property -dict { PACKAGE_PIN N9 IOSTANDARD LVCMOS33 } [get_ports { IO[2] }]
set_property -dict { PACKAGE_PIN M4 IOSTANDARD LVCMOS33 } [get_ports { IO[3] }]
set_property -dict { PACKAGE_PIN M6 IOSTANDARD LVCMOS33 } [get_ports { IO[4] }]
set_property -dict { PACKAGE_PIN M5 IOSTANDARD LVCMOS33 } [get_ports { IO[5] }]
set_property -dict { PACKAGE_PIN E6 IOSTANDARD LVCMOS18 } [get_ports { IO[6] }]

set_property -dict { PACKAGE_PIN G4 IOSTANDARD LVCMOS18 } [get_ports { SW[0] }]
set_property -dict { PACKAGE_PIN H1 IOSTANDARD LVCMOS18 } [get_ports { SW[1] }]

set_property -dict { PACKAGE_PIN M12 IOSTANDARD LVCMOS33 } [get_ports { USB_BE[0] }]
set_property -dict { PACKAGE_PIN N12 IOSTANDARD LVCMOS33 } [get_ports { USB_BE[1] }]
set_property -dict { PACKAGE_PIN K12 IOSTANDARD LVCMOS33 } [get_ports { USB_BE[2] }]
set_property -dict { PACKAGE_PIN M15 IOSTANDARD LVCMOS33 } [get_ports { USB_BE[3] }]
set_property -dict { PACKAGE_PIN A15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[0] }]
set_property -dict { PACKAGE_PIN B16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[1] }]
set_property -dict { PACKAGE_PIN B15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[2] }]
set_property -dict { PACKAGE_PIN C16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[3] }]
set_property -dict { PACKAGE_PIN D14 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[4] }]
set_property -dict { PACKAGE_PIN D15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[5] }]
set_property -dict { PACKAGE_PIN D16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[6] }]
set_property -dict { PACKAGE_PIN E15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[7] }]
set_property -dict { PACKAGE_PIN E16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[8] }]
set_property -dict { PACKAGE_PIN F14 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[9] }]
set_property -dict { PACKAGE_PIN F15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[10] }]
set_property -dict { PACKAGE_PIN G14 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[11] }]
set_property -dict { PACKAGE_PIN G16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[12] }]
set_property -dict { PACKAGE_PIN G15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[13] }]
set_property -dict { PACKAGE_PIN H14 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[14] }]
set_property -dict { PACKAGE_PIN H16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[15] }]
set_property -dict { PACKAGE_PIN G12 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[16] }]
set_property -dict { PACKAGE_PIN H13 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[17] }]
set_property -dict { PACKAGE_PIN J16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[18] }]
set_property -dict { PACKAGE_PIN J15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[19] }]
set_property -dict { PACKAGE_PIN K13 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[20] }]
set_property -dict { PACKAGE_PIN L14 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[21] }]
set_property -dict { PACKAGE_PIN L13 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[22] }]
set_property -dict { PACKAGE_PIN M14 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[23] }]
set_property -dict { PACKAGE_PIN M16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[24] }]
set_property -dict { PACKAGE_PIN N13 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[25] }]
set_property -dict { PACKAGE_PIN N16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[26] }]
set_property -dict { PACKAGE_PIN P15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[27] }]
set_property -dict { PACKAGE_PIN P16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[28] }]
set_property -dict { PACKAGE_PIN R15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[29] }]
set_property -dict { PACKAGE_PIN R16 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[30] }]
set_property -dict { PACKAGE_PIN T15 IOSTANDARD LVCMOS33 } [get_ports { USB_DATA[31] }]
set_property -dict { PACKAGE_PIN N11 IOSTANDARD LVCMOS33 } [get_ports { USB_D_CLK }]
set_property -dict { PACKAGE_PIN D10 IOSTANDARD LVCMOS33 } [get_ports { USB_GPIO[0] }]
set_property -dict { PACKAGE_PIN D11 IOSTANDARD LVCMOS33 } [get_ports { USB_GPIO[1] }]
set_property -dict { PACKAGE_PIN G11 IOSTANDARD LVCMOS33 } [get_ports { USB_NOE }]
set_property -dict { PACKAGE_PIN F13 IOSTANDARD LVCMOS33 } [get_ports { USB_NRD }]
set_property -dict { PACKAGE_PIN E11 IOSTANDARD LVCMOS33 } [get_ports { USB_NRESET }]
set_property -dict { PACKAGE_PIN P13 IOSTANDARD LVCMOS33 } [get_ports { USB_NRXF }]
set_property -dict { PACKAGE_PIN N6 IOSTANDARD LVCMOS33 } [get_ports { USB_NSIWU }]
set_property -dict { PACKAGE_PIN H12 IOSTANDARD LVCMOS33 } [get_ports { USB_NTXE }]
set_property -dict { PACKAGE_PIN H11 IOSTANDARD LVCMOS33 } [get_ports { USB_NWAKEUP }]
set_property -dict { PACKAGE_PIN F12 IOSTANDARD LVCMOS33 } [get_ports { USB_NWR }]

